server:
  port: 8090

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  kafka:
    producer:
      bootstrap-servers: 172.18.60.159:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: producer.serialization.EmailSerializer
      properties:
        buffer:
          memory: 90000000
        max:
          request:
            size: 90000000
      #  An ack is an acknowledgment that the producer gets from a Kafka broker to
      #  ensure that the message has been successfully committed to that broker.
      #  The config acks is the number of acknowledgments the producer needs to
      #  receive before considering a successful commit.
      acks: 1

